name: Fluxo de Trabalho - Dados

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configurar ambiente
        run: |
          echo "API_KEY=${{ secrets.API_KEY }}" >> .env

      - name: Instalar dependências
        run: npm install

      - name: Executar script
        run: node scripts.js
